[phases.setup]
nixPkgs = ["nodejs_18", "python311", "python311Packages.setuptools"]

[phases.install]
cmds = [
  "python3 -m pip install setuptools --break-system-packages || true",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"